CREATE DATABASE IF NOT EXISTS reputation_mvp
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS 'repu'@'%' IDENTIFIED BY 'repu123456';
GRANT ALL PRIVILEGES ON reputation_mvp.* TO 'repu'@'%';
FLUSH PRIVILEGES;
